"""Create Databases

Revision ID: 3302799fc63c
Revises: 
Create Date: 2022-10-10 16:41:15.866150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3302799fc63c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('sys_uid', sa.String(length=512), nullable=False),
    sa.Column('ipaddresses', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('sys_uid')
    )
    op.create_table('repository',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('key'),
    )
    op.create_table('srkv_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=True),
    sa.Column('roll_action', sa.String(length=128), nullable=False),
    sa.Column('roll_value', sa.PickleType(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('uuid', sa.String(length=16), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('srkv_transaction')
    op.drop_table('repository')
    op.drop_table('nodes')
    # ### end Alembic commands ###
