"""Create db

Revision ID: 8461fd9bb3cf
Revises: 
Create Date: 2022-07-08 16:34:57.659431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8461fd9bb3cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('sys_uid', sa.String(length=512), nullable=False),
    sa.Column('ipaddresses', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('sys_uid')
    )
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('value', sa.PickleType(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_repository_key'), 'repository', ['key'], unique=True)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('value', sa.PickleType(), nullable=True),
    sa.Column('roll_action', sa.String(length=128), nullable=True),
    sa.Column('roll_value', sa.PickleType(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text(u"(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_repository_key'), table_name='repository')
    op.drop_table('repository')
    op.drop_table('nodes')
    # ### end Alembic commands ###
